### PR TITLE
docs: fix issues URL

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by michael-o** [comment]
That's a bit ugly now because all tickets are visible in this listing... :-( There might not be a better way now

**Comment by elharo** [comment]
You mean you'd like it to find just maven shared utils bugs and not all Maven shared components bugs?

**Comment by michael-o** [comment]
Exactly

**Comment by elharo** [comment]
Would https://issues.apache.org/jira/browse/MSHARED-282?jql=project%20%3D%20MSHARED%20AND%20component%20%3D%20maven-shared-utils work?

**Comment by michael-o** [comment]
No, this one links to a specific issue.

**Comment by elharo** [comment]
OK, so the existing link is 404 so we need to fix that. Would you prefer to proceed with the link to all of maven shared components or is there a better URL we can use?

**Comment by michael-o** [comment]
Try this one https://issues.apache.org/jira/issues/?jql=project%20%3D%20MSHARED%20AND%20component%20%3D%20maven-shared-utils

**Comment by jira-importer** [comment]
Resolve #254

**Pull request merged**
