### PR TITLE
[MSHARED-862] system independent file separator

### PR DESCRIPTION
**Pull request by elharo**
@rfscholte see if we can make DirectoryScannerTest pass on Windows

### CODE REVIEW

**Comment by michael-o** [comment]
Let me run this too...

**Comment by elharo** [comment]
Interesting. I've never seen that one. Do you also see that one in master?

**Comment by michael-o** [comment]
> 
> 
> Interesting. I've never seen that one. Do you also see that one in master?

Yes, same on master.

**Comment by elharo** [comment]
Build is blue (green) so I'm going to merge.

**Comment by michael-o** [comment]
Ouch, you just have provided 6 junk commits on master. Please avoid that by squashing first. No merge commit since they don't add any benefit for us.

**Comment by elharo** [comment]
Squash commits have a different negative side effect that Robert has asked me to avoid. You should probably bring this up on the dev mailing list, so the community can decide what they want. When a decision is made, the repos can be configured to make the preferred way the only way.

**Comment by michael-o** [comment]
Where did he request this?

**Comment by elharo** [comment]
Slack + email. I don't have a major preference here one way or the other, but I am getting contradictory requests about merging from different committers and PMC members, so let's figure out what everyone is most comfortable with, document that decision, and configure the repos to make it the default or only option.

**Comment by jira-importer** [comment]
Resolve #284

**Pull request merged**
