### PR TITLE
[MSHARED-1196] Bump maven-shared-components from 37 to 39

### PR DESCRIPTION
**Pull request by elharo**
This required a lot of automatic reformatting and a little manual reformatting to make spotless happy

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
All license headers in Java files are duplicated.

**Comment by elharo** [comment]
Ick. I blame spotless, which is not so spotless. Let me see if I can fix that.

**Comment by elharo** [comment]
OK, I think the duplicate licenses are removed. I am very much not a fan of spotless at this point.

**Review by elharo — COMMENTED** [review]
Should be ready for another review. This PR involves a lot more churn than I like, but it appears to be necessary to keep up with the Maven parent POM which is now enforcing a different code style than we used to use.

**Comment by elharo** [comment]
Looks like a few broken Javadoc cross-ref links trip only one of our CIs. Fixing...


```
                      ^
/home/runner/work/maven-shared-utils/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/logging/package-info.java:26: error: reference not found
 * {@link org.apache.maven.shared.utils.logging.LoggerLevelRenderer LoggerLevelRenderer}.
          ^
/home/runner/work/maven-shared-utils/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/logging/package-info.java:28: error: reference not found
 * {@link org.apache.maven.shared.utils.logging.MessageUtils MessageUtils} gives access to these builders.
          ^
/home/runner/work/maven-shared-utils/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/logging/package-info.java:35: error: reference not found
 * {@link org.apache.maven.shared.utils.logging.LoggerLevelRenderer logger level rendering},</li>
          ^
/home/runner/work/maven-shared-utils/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/logging/package-info.java:37: error: reference not found
 * and <code>project</code> for {@link org.apache.maven.shared.utils.logging.MessageBuilder message content}</li>
```

**Review by michael-o — APPROVED** [review]

**Pull request merged**
