### PR TITLE
[MSHARED-1273] clean up API doc and exceptions

### PR DESCRIPTION
**Pull request by elharo**
still trying to figure out how best to replace these methods completely

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
Maybe commit message should contain ... `and do not throw IOException` as jira issue
we don't add exceptions

**Comment by slachiewicz** [comment]
so it will be breaking change

**Comment by elharo** [comment]
It isn't throwing IOException now. This PR brings the throws clauses in sync with what the code was already (not) doing.

**Comment by slachiewicz** [comment]
external code that use this methods and catch exception will be broken after update

**Comment by elharo** [comment]
You're right. I think I was mixing up catch blocks for unthrown exceptions and throws clauses for unthrown exceptions in my head. I'll send another PR to clean this up.

**Comment by slachiewicz** [comment]
No problem. You just have to release minor versions and not bugfix

**Pull request merged**
