### PR TITLE
[MSHARED-1109] fix broken IT after previous refactoring

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@michael-o That should fix the broken IT, which regressed due to https://github.com/apache/maven-shared-utils/commit/8822bea7d21d53b106a696fd95f10c494ce20c7a.

**Comment by michael-o** [comment]
Charming...

**Comment by kwin** [comment]
The master build and also this PR cannot be built currently due to another issue with m-resources-p

**Comment by michael-o** [comment]
> The master build and also this PR cannot be built currently due to another issue with m-resources-p

Chicken and egg we'll fix in the next round...

**Comment by jira-importer** [comment]
Resolve #310

**Pull request closed without merging**
