### PR TITLE
[MSHARED-983] Drop plexus container default

### PR DESCRIPTION
**Pull request by cstamas**
https://issues.apache.org/jira/browse/MSHARED-983

The complete container was only here to make use of AbstractLogEnabled
ancient class, that uses ancient logging.

Changes:
* Drop p-c-d
* Reorder deps by scope, test last.

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by elharo — COMMENTED** [review]
This change is not API compatible. It deserves at least a minor version update and preferably a major version update.

**Review by elharo — APPROVED** [review]
Is there a PMC member who can create a maven-shared-utils 4.0.0 release label in Jira? or perhaps change the 3.4.0 label to 4.0.0?

**Comment by cstamas** [comment]
> Is there a PMC member who can create a maven-shared-utils 4.0.0 release label in Jira? or perhaps change the 3.4.0 label to 4.0.0?

created https://issues.apache.org/jira/projects/MSHARED/versions/12350135

**Comment by slachiewicz** [comment]
Nice,with this new version we can also require java 8 (as separate ticket)

**Comment by elharo** [comment]
running through jenkins: https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-shared-utils/job/MSHARED-983/

**Pull request merged**
