### PR TITLE
Windows 9X is long dead

### PR DESCRIPTION
**Pull request by elharo**
@slawekjaranowski

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Maybe `org.apache.maven.shared.utils.cli.shell.CommandShell` should be also removed - I don't see usage of it in this project.

**Comment by michael-o** [comment]
I agree with @slawekjaranowski

**Comment by elharo** [comment]
Eventually, yes. However it's public API so I don't want to remove it until it's been deprecated for a while longer and ideally we're ready for a major version bump.

**Comment by slawekjaranowski** [comment]
I afraid that this never will happened developers don't look for deprecated ...
The same result will be remove it and release next major version.

Looking for this class on GitHub I found 4 repositories where it is used,  one of them is archived, two don't have any releases so impact will not be huge.

**Comment by elharo** [comment]
I'm not comfortable removing public API without reasonable notice. Sounds like there are existing uses.

**Comment by slawekjaranowski** [comment]
So please deprecate class with reason. 

Another case is that apache components don't have any release plan / calendar so nobody know when next release will be placed.
Also there is no policy about clearing deprecated items.

**Comment by michael-o** [comment]
@elharo This won't even run in Windows 9x because there isn't Java 7 for.

**Comment by elharo** [comment]
That still doesn't mean we should break the build of projects that have this in their tree. Deprecate and warn them. We can take it out in a few releases.

**Comment by slachiewicz** [comment]
`CmdShell` was marked as Deprecated with MSHARED-860 in https://github.com/apache/maven-shared-utils/commit/cb448b90918a5e894c38b86d00d402638f195502 and released with 3.3.3 version.

**Comment by MartinKanters** [comment]
@elharo I guess we can merge this then, right? Nobody had any objections against your code, apart from that we had to deprecate the classes, which @slachiewicz pointed out was done last year.

**Review by slachiewicz — APPROVED** [review]

**Pull request merged**
