### PR TITLE
remove unused plexus dependency

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by MartinKanters** [comment]
@elharo Is there any specific reason @michael-o should look at this? IMO I would say that if the code still compiles without this dependency, we should be good in general?

**Comment by elharo** [comment]
Anyone can review. I try to request reviews roughly round robin amongst active committers unless I believe there's a particular reason someone might be interested in a PR.

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
Build failed:

------

[ERROR] /home/jenkins/workspace/en-box_maven-shared-utils_master@2/m/src/main/java/org/apache/maven/shared/utils/cli/javatool/AbstractJavaTool.java:[28,35] package org.codehaus.plexus.logging does not exist

**Comment by MartinKanters** [comment]
@slachiewicz @elharo looks like we could use GitHub Actions in this repo.. :) 
Imo we should revert this PR, do you guys have any concern with that?

**Pull request merged**
