### PR TITLE
[MSHARED-750] - Unbalanced quotes in command with escaped double quot…

### PR DESCRIPTION
**Pull request by KathrynN**
…ation mark

### CODE REVIEW

**Comment by khmarbaise** [comment]
Is this ready for integration from your side ?

**Comment by KathrynN** [comment]
Yep!  As soon as you're happy with it.

**Comment by khmarbaise** [comment]
Successful build. Also merged into master
* https://gitbox.apache.org/repos/asf?p=maven-shared-utils.git;a=commitdiff;h=336594396f2e9be8a572100e30a611f8123a837d
* https://issues.apache.org/jira/browse/MSHARED-750

Thanks for your contribution.

**Comment by KathrynN** [comment]
Was the email better this time?
Thank you for your swift response!

**Comment by khmarbaise** [comment]
Hi Kathryn, If you look on the repository on master you see the your image ...which means GitHub has identified it correctly..Thanks for fixing this...

**Pull request closed without merging**
