### PR TITLE
[MSHARED-1289] Deprecate library

### PR DESCRIPTION
**Pull request by kwin**
TODO:
Find replacements for 

1. `org.apache.maven.shared.utils.cli.javatool` and
2. `org.apache.maven.shared.utils.logging`

### CODE REVIEW

**Review by elharo — CHANGES_REQUESTED** [review]
One more time: No. This is exactly wrong. We want to get rid of plexus, not use it more,.

**Comment by kwin** [comment]
Feel free to comment and decline but closing some other committers PR is a no go for me. Also you didn’t state no on the referenced mailing list thread. Reality is that plexus utils got more attention the last years and bugfixes were never backported to maven-shared-utils. We cannot afford maintaining both!

**Comment by elharo** [comment]
We went through this a few weeks ago, This is not new. 

I agree we can't maintain both. Plexus needs to go. That's been decided at least twice and we can't keep relitigating it.

**Comment by kwin** [comment]
Who decided and when? I know the original intent but that failed clearly. Also only 4 committers commented on the aforementioned thread. 3 in favor and you.

**Comment by elharo** [comment]
see https://github.com/apache/maven-shared-utils/pull/154 from less than a month ago.

**Comment by elharo** [comment]
Sorry, I was wrong. It was a month and three days ago; but I still don;t want to have to close this same PR every month. Your time would be better spent replacing existing usages of plexus throughout maven or reviewing unreviewed PRs in this repo, among otehr things.

**Review by slachiewicz — APPROVED** [review]

**Comment by elharo** [comment]
Still a hard no on this one. This needs to be dealt with one piece at a time, not as a single PR that deprecates things that are in use and that we don't have replacements for. Even more importantly, we need to eliminate plexus-utils, not reintroduce it. The foggy ownership and licensing story make it infeasible for Apache projects.

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
I agree with @elharo we should think rather about deprecate plexus-utils especially with licenses issues

So we should deprecate one by one feature which has replacement in JDK or other commons library.

**Comment by slachiewicz** [comment]
Only packages listed by Konrad above must be kept in this lib, or we can find a replacement. All others are just duplicates.

**Pull request closed without merging**
