### PR TITLE
[MSHARED-826] Require Java 7

### PR DESCRIPTION
**Pull request by mthmulders**
As suggested by @rfscholte in [MSHARED-826](https://issues.apache.org/jira/browse/MSHARED-826): updated to maven-parent:33 and set property `javaVersion` to 7.

### CODE REVIEW

**Comment by rfscholte** [comment]
The OS related tests need to be changed, see https://builds.apache.org/job/maven-box/job/maven-shared-utils/job/MSHARED-826/test_results_analyzer/
With Java 12 you cannot change the System properties anymore that were provided by Java at startup.

**Comment by Tibor17** [comment]
@rfscholte 
The Java 12 has a new API to override system properties at runtime?

**Comment by rfscholte** [comment]
@Tibor17 No, there's just a set of properties that are marked as static properties: they can only be set at startup and cannot be changed afterwards. https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/jdk/internal/util/StaticProperty.java shows a list.
However, it doesn't mention the os properties... might need some extra analysis.

**Comment by mthmulders** [comment]
> The OS related tests need to be changed

I assume this is also the case on master? Since this PR doesn't touch a single test...

**Comment by Tibor17** [comment]
@mthmulders 
One thing is to set higher Java 1.7 and another thing is to use Java 1.7 features in Java code.
You know the features of Java 1.7.
Try to open another PR where you complete this improvement in code; otherwise bytecode version does not have any value for nobody. Thx for your work!

**Comment by mthmulders** [comment]
Thanks for the suggestion. I deliberately didn't want to mix the two (requiring Java 1.7 and using its new features). Java 7 is required for [MSHARED-822](https://issues.apache.org/jira/browse/MSHARED-822) / #6, so we'll soon make use of at least some of the new features.

**Comment by jira-importer** [comment]
Resolve #281

**Pull request merged**
