### PR TITLE
[MSHARED-749] - Commandline does not thrown CommandLineException when…

### PR DESCRIPTION
**Pull request by KathrynN**
… uneven number of quotation marks used

### CODE REVIEW

**Comment by khmarbaise** [comment]
CI build started https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-shared-utils/job/MSHARED-749/

**Comment by khmarbaise** [comment]
Successful CI build and merged to master.
 * https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-shared-utils/job/MSHARED-749/
 * https://gitbox.apache.org/repos/asf?p=maven-shared-utils.git;a=commitdiff;h=43210ae850b9c2d9426fc850aa9b9ad71d543294

Thank you for your contribution.

**Comment by KathrynN** [comment]
Thanks Karl!
I know, I have a problem ;)

**Comment by khmarbaise** [comment]
Which one ?

**Pull request closed without merging**
